In [2]:
import numpy as np
filedata = np.genfromtxt('random_numbers.txt', delimiter=',').astype('int32')
filedata

array([[723, 802, 814, 534,  50, 981, 595, 459, 626, 914],
       [ 70,  28, 684, 189, 948, 474, 904, 865, 697, 783],
       [446, 948, 163, 440, 879,  55,  72, 102, 665, 580],
       [886, 239, 329, 609, 169, 960, 693, 327, 212, 440],
       [558, 665, 491, 555, 548, 644, 833, 434, 859, 677],
       [999, 642, 914, 303, 116, 238, 338, 701, 579, 149],
       [972,  27, 429, 284, 295, 341, 600, 872, 194,  81],
       [401, 837, 123, 151, 972,  98, 230, 725, 225, 924],
       [ 49, 813, 203, 682, 476, 396, 162, 362, 331,  45],
       [405, 680, 561, 376, 430, 927,  10, 468, 453, 160]], dtype=int32)

In [3]:
np.max(filedata)

999

In [4]:
np.min(filedata)

10

In [5]:
np.sum(filedata)

49367

In [6]:
np.mean(filedata, axis=1)

array([649.8, 564.2, 435. , 486.4, 626.4, 497.9, 409.5, 468.6, 351.9,
       447. ])

In [7]:
np.max(filedata[0, :])

981

In [8]:
filedata[(filedata %3==0) & (filedata%5==0)]

array([960, 555, 600, 225,  45, 405], dtype=int32)

In [9]:
filedata[np.sum(filedata,axis=1) == np.max(np.sum(filedata,axis=1))]

array([[723, 802, 814, 534,  50, 981, 595, 459, 626, 914]], dtype=int32)

In [10]:
filedata[np.linalg.inv(filedata) == np.min(np.linalg.inv(filedata))]

array([600], dtype=int32)

In [11]:
center_array = filedata[4:6, 4:6]

In [12]:
center_array

array([[548, 644],
       [116, 238]], dtype=int32)